const cart = [
    {
        id: 1,
        category: "Drinks",
        img: 'cola.png',
        titlle: "Coca-cola 0.5",
        decs: "Газированный напиток",
        count: 1,
        price: 500,
        priceTotal: 500,
    },
    {
        id: 2,
        category: "Drinks",
        img: 'spirite.jpeg',
        titlle: 'Sprite 0.5',
        decs: "Газированный напиток",
        count: 1,
        price: 500,
        priceTotal: 500,
    },
    {
        id: 3,
        category: "Drinks",
        img: 'bon.avif',
        titlle: 'BonAqua 0.5',
        decs: "Газированный напиток",
        count: 1,
        price: 350,
        priceTotal: 350,
    },
   /*  {
        id: 4,
        category: "Snacks",
        img: 'snicers.webp',
        titlle: 'Snickers small',
        count: 1,
        price: 450,
        priceTotal: 350,
    },
    {
        id: 5,
        category: "Snacks",
        img: 'twix.webp',
        titlle: 'Twix small',
        count: 1,
        price: 450,
        priceTotal: 450,
    },
    {
        id: 6,
        category: "Food",
        img: 'sandwich.jpg',
        titlle: 'Sandwich',
        count: 1,
        price: 770,
        priceTotal: 770,
    },
    {
        id: 7,
        category: "Food",
        img: 'food.avif',
        titlle: 'Food',
        count: 1,
        price: 1500,
        priceTotal: 1500,
    }, */
];

export default cart;
